[variables]
NODE_VERSION = "22.15.1"

[phases.install]
cmds = ["rm -rf node_modules package-lock.json && npm install --no-fund --no-audit --ignore-scripts"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
